/********************************************************************************
** Form generated from reading UI file 'simulator.ui'
**
** Created by: Qt User Interface Compiler version 5.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SIMULATOR_H
#define UI_SIMULATOR_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QPushButton *Button_reset;
    QPushButton *Button_next;
    QPushButton *Button_load;
    QTabWidget *Monitor;
    QWidget *Main;
    QTabWidget *Pipeline;
    QWidget *Fetch;
    QGroupBox *groupBox_5;
    QTextBrowser *F_predPC;
    QGroupBox *groupBox_6;
    QTextBrowser *f_predPC;
    QGroupBox *groupBox_7;
    QTextBrowser *F_STAT;
    QGroupBox *groupBox_8;
    QTextBrowser *F_stall;
    QGroupBox *groupBox_9;
    QTextBrowser *F_bubble;
    QGroupBox *groupBox_13;
    QTextBrowser *F_ifun;
    QGroupBox *groupBox_14;
    QTextBrowser *F_icode;
    QWidget *Decode;
    QGroupBox *groupBox_17;
    QTextBrowser *D_valP;
    QGroupBox *groupBox_18;
    QTextBrowser *D_bubble;
    QGroupBox *groupBox_19;
    QTextBrowser *D_stall;
    QGroupBox *groupBox_20;
    QTextBrowser *D_rB;
    QGroupBox *groupBox_21;
    QTextBrowser *D_STAT;
    QGroupBox *groupBox_23;
    QTextBrowser *D_icode;
    QGroupBox *groupBox_24;
    QTextBrowser *D_rA;
    QGroupBox *groupBox_25;
    QTextBrowser *D_valC;
    QGroupBox *groupBox_26;
    QTextBrowser *D_ifun;
    QWidget *Execute;
    QGroupBox *groupBox_28;
    QTextBrowser *E_stall;
    QGroupBox *groupBox_29;
    QTextBrowser *E_STAT;
    QGroupBox *groupBox_30;
    QTextBrowser *E_bubble;
    QGroupBox *groupBox_31;
    QTextBrowser *E_ifun;
    QGroupBox *groupBox_32;
    QTextBrowser *E_valC;
    QGroupBox *groupBox_33;
    QTextBrowser *E_dstM;
    QGroupBox *groupBox_34;
    QTextBrowser *E_dstE;
    QGroupBox *groupBox_35;
    QTextBrowser *E_valA;
    QGroupBox *groupBox_36;
    QTextBrowser *E_icode;
    QGroupBox *groupBox_37;
    QTextBrowser *E_valB;
    QGroupBox *groupBox_38;
    QTextBrowser *E_srcA;
    QGroupBox *groupBox_39;
    QTextBrowser *E_srcB;
    QWidget *Memory;
    QGroupBox *groupBox_69;
    QTextBrowser *M_dstM;
    QGroupBox *groupBox_70;
    QTextBrowser *M_icode;
    QGroupBox *groupBox_72;
    QTextBrowser *M_bubble;
    QGroupBox *groupBox_73;
    QTextBrowser *M_valE;
    QGroupBox *groupBox_74;
    QTextBrowser *M_dstE;
    QGroupBox *groupBox_75;
    QTextBrowser *M_valA;
    QGroupBox *groupBox_77;
    QTextBrowser *M_Cnd;
    QGroupBox *groupBox_79;
    QTextBrowser *M_STAT;
    QGroupBox *groupBox_80;
    QTextBrowser *M_stall;
    QWidget *Write_back;
    QGroupBox *groupBox_76;
    QTextBrowser *W_bubble;
    QGroupBox *groupBox_78;
    QTextBrowser *W_valE;
    QGroupBox *groupBox_71;
    QTextBrowser *W_dstM;
    QGroupBox *groupBox_81;
    QTextBrowser *W_icode;
    QGroupBox *groupBox_82;
    QTextBrowser *W_dstE;
    QGroupBox *groupBox_83;
    QTextBrowser *W_stall;
    QGroupBox *groupBox_84;
    QTextBrowser *W_valM;
    QGroupBox *groupBox_85;
    QTextBrowser *W_STAT;
    QGroupBox *groupBox;
    QTextBrowser *STAT;
    QGroupBox *groupBox_2;
    QGroupBox *ZFBOX;
    QTextBrowser *ZF;
    QGroupBox *OFBOX;
    QTextBrowser *OF;
    QGroupBox *SFBOX;
    QTextBrowser *SF;
    QGroupBox *CFBOX;
    QTextBrowser *CF;
    QGroupBox *groupBox_3;
    QTextBrowser *cycle;
    QGroupBox *groupBox_4;
    QLabel *label_ebx;
    QLabel *label_eax;
    QLabel *label_ecx;
    QLabel *label_edx;
    QTextBrowser *text_eax;
    QTextBrowser *text_ecx;
    QTextBrowser *text_edx;
    QTextBrowser *text_ebx;
    QTextBrowser *text_esp;
    QLabel *label_ebp;
    QLabel *label_esi;
    QLabel *label_edi;
    QLabel *label_esp;
    QTextBrowser *text_edi;
    QTextBrowser *text_esi;
    QTextBrowser *text_ebp;
    QWidget *Operation;
    QTabWidget *Pipeline_2;
    QWidget *Fetch_2;
    QTextBrowser *f_opt;
    QWidget *Decode_2;
    QTextBrowser *d_opt;
    QWidget *Execute_2;
    QTextBrowser *e_opt;
    QWidget *Memory_2;
    QTextBrowser *m_opt;
    QWidget *Write_back_2;
    QTextBrowser *w_opt;
    QWidget *Memory1;
    QTextBrowser *memorymonitor;
    QLineEdit *path;
    QPushButton *Button_run;
    QPushButton *Button_stop;
    QGroupBox *groupBox_10;
    QSlider *speed;
    QLabel *label;
    QLabel *nowspeed;
    QLineEdit *path_code;
    QPushButton *Button_code;
    QPushButton *Button_clear;
    QGroupBox *groupBox_11;
    QTextBrowser *Code;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(946, 709);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        Button_reset = new QPushButton(centralWidget);
        Button_reset->setObjectName(QStringLiteral("Button_reset"));
        Button_reset->setGeometry(QRect(40, 590, 91, 31));
        Button_next = new QPushButton(centralWidget);
        Button_next->setObjectName(QStringLiteral("Button_next"));
        Button_next->setGeometry(QRect(140, 590, 91, 31));
        Button_load = new QPushButton(centralWidget);
        Button_load->setObjectName(QStringLiteral("Button_load"));
        Button_load->setGeometry(QRect(40, 630, 91, 31));
        Monitor = new QTabWidget(centralWidget);
        Monitor->setObjectName(QStringLiteral("Monitor"));
        Monitor->setGeometry(QRect(440, 20, 501, 671));
        Main = new QWidget();
        Main->setObjectName(QStringLiteral("Main"));
        Pipeline = new QTabWidget(Main);
        Pipeline->setObjectName(QStringLiteral("Pipeline"));
        Pipeline->setGeometry(QRect(20, 20, 461, 311));
        Fetch = new QWidget();
        Fetch->setObjectName(QStringLiteral("Fetch"));
        groupBox_5 = new QGroupBox(Fetch);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(110, 20, 101, 61));
        F_predPC = new QTextBrowser(groupBox_5);
        F_predPC->setObjectName(QStringLiteral("F_predPC"));
        F_predPC->setGeometry(QRect(10, 20, 81, 31));
        groupBox_6 = new QGroupBox(Fetch);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(210, 20, 101, 61));
        f_predPC = new QTextBrowser(groupBox_6);
        f_predPC->setObjectName(QStringLiteral("f_predPC"));
        f_predPC->setGeometry(QRect(10, 20, 81, 31));
        groupBox_7 = new QGroupBox(Fetch);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(10, 20, 101, 61));
        F_STAT = new QTextBrowser(groupBox_7);
        F_STAT->setObjectName(QStringLiteral("F_STAT"));
        F_STAT->setGeometry(QRect(10, 20, 81, 31));
        groupBox_8 = new QGroupBox(Fetch);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(339, 140, 101, 61));
        F_stall = new QTextBrowser(groupBox_8);
        F_stall->setObjectName(QStringLiteral("F_stall"));
        F_stall->setGeometry(QRect(10, 20, 81, 31));
        groupBox_9 = new QGroupBox(Fetch);
        groupBox_9->setObjectName(QStringLiteral("groupBox_9"));
        groupBox_9->setGeometry(QRect(340, 210, 101, 61));
        F_bubble = new QTextBrowser(groupBox_9);
        F_bubble->setObjectName(QStringLiteral("F_bubble"));
        F_bubble->setGeometry(QRect(10, 20, 81, 31));
        groupBox_13 = new QGroupBox(Fetch);
        groupBox_13->setObjectName(QStringLiteral("groupBox_13"));
        groupBox_13->setGeometry(QRect(10, 160, 101, 61));
        F_ifun = new QTextBrowser(groupBox_13);
        F_ifun->setObjectName(QStringLiteral("F_ifun"));
        F_ifun->setGeometry(QRect(10, 20, 81, 31));
        groupBox_14 = new QGroupBox(Fetch);
        groupBox_14->setObjectName(QStringLiteral("groupBox_14"));
        groupBox_14->setGeometry(QRect(10, 90, 101, 61));
        F_icode = new QTextBrowser(groupBox_14);
        F_icode->setObjectName(QStringLiteral("F_icode"));
        F_icode->setGeometry(QRect(10, 20, 81, 31));
        Pipeline->addTab(Fetch, QString());
        groupBox_5->raise();
        groupBox_6->raise();
        groupBox_7->raise();
        groupBox_8->raise();
        groupBox_9->raise();
        groupBox_13->raise();
        groupBox_14->raise();
        Decode = new QWidget();
        Decode->setObjectName(QStringLiteral("Decode"));
        groupBox_17 = new QGroupBox(Decode);
        groupBox_17->setObjectName(QStringLiteral("groupBox_17"));
        groupBox_17->setGeometry(QRect(210, 90, 101, 61));
        D_valP = new QTextBrowser(groupBox_17);
        D_valP->setObjectName(QStringLiteral("D_valP"));
        D_valP->setGeometry(QRect(10, 20, 81, 31));
        groupBox_18 = new QGroupBox(Decode);
        groupBox_18->setObjectName(QStringLiteral("groupBox_18"));
        groupBox_18->setGeometry(QRect(340, 210, 101, 61));
        D_bubble = new QTextBrowser(groupBox_18);
        D_bubble->setObjectName(QStringLiteral("D_bubble"));
        D_bubble->setGeometry(QRect(10, 20, 81, 31));
        groupBox_19 = new QGroupBox(Decode);
        groupBox_19->setObjectName(QStringLiteral("groupBox_19"));
        groupBox_19->setGeometry(QRect(339, 140, 101, 61));
        D_stall = new QTextBrowser(groupBox_19);
        D_stall->setObjectName(QStringLiteral("D_stall"));
        D_stall->setGeometry(QRect(10, 20, 81, 31));
        groupBox_20 = new QGroupBox(Decode);
        groupBox_20->setObjectName(QStringLiteral("groupBox_20"));
        groupBox_20->setGeometry(QRect(110, 90, 101, 61));
        D_rB = new QTextBrowser(groupBox_20);
        D_rB->setObjectName(QStringLiteral("D_rB"));
        D_rB->setGeometry(QRect(10, 20, 81, 31));
        groupBox_21 = new QGroupBox(Decode);
        groupBox_21->setObjectName(QStringLiteral("groupBox_21"));
        groupBox_21->setGeometry(QRect(10, 20, 101, 61));
        D_STAT = new QTextBrowser(groupBox_21);
        D_STAT->setObjectName(QStringLiteral("D_STAT"));
        D_STAT->setGeometry(QRect(10, 20, 81, 31));
        groupBox_23 = new QGroupBox(Decode);
        groupBox_23->setObjectName(QStringLiteral("groupBox_23"));
        groupBox_23->setGeometry(QRect(10, 90, 101, 61));
        D_icode = new QTextBrowser(groupBox_23);
        D_icode->setObjectName(QStringLiteral("D_icode"));
        D_icode->setGeometry(QRect(10, 20, 81, 31));
        groupBox_24 = new QGroupBox(Decode);
        groupBox_24->setObjectName(QStringLiteral("groupBox_24"));
        groupBox_24->setGeometry(QRect(110, 20, 101, 61));
        D_rA = new QTextBrowser(groupBox_24);
        D_rA->setObjectName(QStringLiteral("D_rA"));
        D_rA->setGeometry(QRect(10, 20, 81, 31));
        groupBox_25 = new QGroupBox(Decode);
        groupBox_25->setObjectName(QStringLiteral("groupBox_25"));
        groupBox_25->setGeometry(QRect(210, 20, 101, 61));
        D_valC = new QTextBrowser(groupBox_25);
        D_valC->setObjectName(QStringLiteral("D_valC"));
        D_valC->setGeometry(QRect(10, 20, 81, 31));
        groupBox_26 = new QGroupBox(Decode);
        groupBox_26->setObjectName(QStringLiteral("groupBox_26"));
        groupBox_26->setGeometry(QRect(10, 160, 101, 61));
        D_ifun = new QTextBrowser(groupBox_26);
        D_ifun->setObjectName(QStringLiteral("D_ifun"));
        D_ifun->setGeometry(QRect(10, 20, 81, 31));
        Pipeline->addTab(Decode, QString());
        Execute = new QWidget();
        Execute->setObjectName(QStringLiteral("Execute"));
        groupBox_28 = new QGroupBox(Execute);
        groupBox_28->setObjectName(QStringLiteral("groupBox_28"));
        groupBox_28->setGeometry(QRect(339, 140, 101, 61));
        E_stall = new QTextBrowser(groupBox_28);
        E_stall->setObjectName(QStringLiteral("E_stall"));
        E_stall->setGeometry(QRect(10, 20, 81, 31));
        groupBox_29 = new QGroupBox(Execute);
        groupBox_29->setObjectName(QStringLiteral("groupBox_29"));
        groupBox_29->setGeometry(QRect(10, 20, 101, 61));
        E_STAT = new QTextBrowser(groupBox_29);
        E_STAT->setObjectName(QStringLiteral("E_STAT"));
        E_STAT->setGeometry(QRect(10, 20, 81, 31));
        groupBox_30 = new QGroupBox(Execute);
        groupBox_30->setObjectName(QStringLiteral("groupBox_30"));
        groupBox_30->setGeometry(QRect(340, 210, 101, 61));
        E_bubble = new QTextBrowser(groupBox_30);
        E_bubble->setObjectName(QStringLiteral("E_bubble"));
        E_bubble->setGeometry(QRect(10, 20, 81, 31));
        groupBox_31 = new QGroupBox(Execute);
        groupBox_31->setObjectName(QStringLiteral("groupBox_31"));
        groupBox_31->setGeometry(QRect(10, 160, 101, 61));
        E_ifun = new QTextBrowser(groupBox_31);
        E_ifun->setObjectName(QStringLiteral("E_ifun"));
        E_ifun->setGeometry(QRect(10, 20, 81, 31));
        groupBox_32 = new QGroupBox(Execute);
        groupBox_32->setObjectName(QStringLiteral("groupBox_32"));
        groupBox_32->setGeometry(QRect(110, 20, 101, 61));
        E_valC = new QTextBrowser(groupBox_32);
        E_valC->setObjectName(QStringLiteral("E_valC"));
        E_valC->setGeometry(QRect(10, 20, 81, 31));
        groupBox_33 = new QGroupBox(Execute);
        groupBox_33->setObjectName(QStringLiteral("groupBox_33"));
        groupBox_33->setGeometry(QRect(210, 90, 101, 61));
        E_dstM = new QTextBrowser(groupBox_33);
        E_dstM->setObjectName(QStringLiteral("E_dstM"));
        E_dstM->setGeometry(QRect(10, 20, 81, 31));
        groupBox_34 = new QGroupBox(Execute);
        groupBox_34->setObjectName(QStringLiteral("groupBox_34"));
        groupBox_34->setGeometry(QRect(210, 20, 101, 61));
        E_dstE = new QTextBrowser(groupBox_34);
        E_dstE->setObjectName(QStringLiteral("E_dstE"));
        E_dstE->setGeometry(QRect(10, 20, 81, 31));
        groupBox_35 = new QGroupBox(Execute);
        groupBox_35->setObjectName(QStringLiteral("groupBox_35"));
        groupBox_35->setGeometry(QRect(110, 90, 101, 61));
        E_valA = new QTextBrowser(groupBox_35);
        E_valA->setObjectName(QStringLiteral("E_valA"));
        E_valA->setGeometry(QRect(10, 20, 81, 31));
        groupBox_36 = new QGroupBox(Execute);
        groupBox_36->setObjectName(QStringLiteral("groupBox_36"));
        groupBox_36->setGeometry(QRect(10, 90, 101, 61));
        E_icode = new QTextBrowser(groupBox_36);
        E_icode->setObjectName(QStringLiteral("E_icode"));
        E_icode->setGeometry(QRect(10, 20, 81, 31));
        groupBox_37 = new QGroupBox(Execute);
        groupBox_37->setObjectName(QStringLiteral("groupBox_37"));
        groupBox_37->setGeometry(QRect(110, 160, 101, 61));
        E_valB = new QTextBrowser(groupBox_37);
        E_valB->setObjectName(QStringLiteral("E_valB"));
        E_valB->setGeometry(QRect(10, 20, 81, 31));
        groupBox_38 = new QGroupBox(Execute);
        groupBox_38->setObjectName(QStringLiteral("groupBox_38"));
        groupBox_38->setGeometry(QRect(210, 160, 101, 61));
        E_srcA = new QTextBrowser(groupBox_38);
        E_srcA->setObjectName(QStringLiteral("E_srcA"));
        E_srcA->setGeometry(QRect(10, 20, 81, 31));
        groupBox_39 = new QGroupBox(Execute);
        groupBox_39->setObjectName(QStringLiteral("groupBox_39"));
        groupBox_39->setGeometry(QRect(210, 220, 101, 61));
        E_srcB = new QTextBrowser(groupBox_39);
        E_srcB->setObjectName(QStringLiteral("E_srcB"));
        E_srcB->setGeometry(QRect(10, 20, 81, 31));
        Pipeline->addTab(Execute, QString());
        Memory = new QWidget();
        Memory->setObjectName(QStringLiteral("Memory"));
        groupBox_69 = new QGroupBox(Memory);
        groupBox_69->setObjectName(QStringLiteral("groupBox_69"));
        groupBox_69->setGeometry(QRect(210, 90, 101, 61));
        M_dstM = new QTextBrowser(groupBox_69);
        M_dstM->setObjectName(QStringLiteral("M_dstM"));
        M_dstM->setGeometry(QRect(10, 20, 81, 31));
        groupBox_70 = new QGroupBox(Memory);
        groupBox_70->setObjectName(QStringLiteral("groupBox_70"));
        groupBox_70->setGeometry(QRect(10, 90, 101, 61));
        M_icode = new QTextBrowser(groupBox_70);
        M_icode->setObjectName(QStringLiteral("M_icode"));
        M_icode->setGeometry(QRect(10, 20, 81, 31));
        groupBox_72 = new QGroupBox(Memory);
        groupBox_72->setObjectName(QStringLiteral("groupBox_72"));
        groupBox_72->setGeometry(QRect(340, 210, 101, 61));
        M_bubble = new QTextBrowser(groupBox_72);
        M_bubble->setObjectName(QStringLiteral("M_bubble"));
        M_bubble->setGeometry(QRect(10, 20, 81, 31));
        groupBox_73 = new QGroupBox(Memory);
        groupBox_73->setObjectName(QStringLiteral("groupBox_73"));
        groupBox_73->setGeometry(QRect(110, 20, 101, 61));
        M_valE = new QTextBrowser(groupBox_73);
        M_valE->setObjectName(QStringLiteral("M_valE"));
        M_valE->setGeometry(QRect(10, 20, 81, 31));
        groupBox_74 = new QGroupBox(Memory);
        groupBox_74->setObjectName(QStringLiteral("groupBox_74"));
        groupBox_74->setGeometry(QRect(210, 20, 101, 61));
        M_dstE = new QTextBrowser(groupBox_74);
        M_dstE->setObjectName(QStringLiteral("M_dstE"));
        M_dstE->setGeometry(QRect(10, 20, 81, 31));
        groupBox_75 = new QGroupBox(Memory);
        groupBox_75->setObjectName(QStringLiteral("groupBox_75"));
        groupBox_75->setGeometry(QRect(110, 90, 101, 61));
        M_valA = new QTextBrowser(groupBox_75);
        M_valA->setObjectName(QStringLiteral("M_valA"));
        M_valA->setGeometry(QRect(10, 20, 81, 31));
        groupBox_77 = new QGroupBox(Memory);
        groupBox_77->setObjectName(QStringLiteral("groupBox_77"));
        groupBox_77->setGeometry(QRect(10, 160, 101, 61));
        M_Cnd = new QTextBrowser(groupBox_77);
        M_Cnd->setObjectName(QStringLiteral("M_Cnd"));
        M_Cnd->setGeometry(QRect(10, 20, 81, 31));
        groupBox_79 = new QGroupBox(Memory);
        groupBox_79->setObjectName(QStringLiteral("groupBox_79"));
        groupBox_79->setGeometry(QRect(10, 20, 101, 61));
        M_STAT = new QTextBrowser(groupBox_79);
        M_STAT->setObjectName(QStringLiteral("M_STAT"));
        M_STAT->setGeometry(QRect(10, 20, 81, 31));
        groupBox_80 = new QGroupBox(Memory);
        groupBox_80->setObjectName(QStringLiteral("groupBox_80"));
        groupBox_80->setGeometry(QRect(339, 140, 101, 61));
        M_stall = new QTextBrowser(groupBox_80);
        M_stall->setObjectName(QStringLiteral("M_stall"));
        M_stall->setGeometry(QRect(10, 20, 81, 31));
        Pipeline->addTab(Memory, QString());
        Write_back = new QWidget();
        Write_back->setObjectName(QStringLiteral("Write_back"));
        groupBox_76 = new QGroupBox(Write_back);
        groupBox_76->setObjectName(QStringLiteral("groupBox_76"));
        groupBox_76->setGeometry(QRect(340, 210, 101, 61));
        W_bubble = new QTextBrowser(groupBox_76);
        W_bubble->setObjectName(QStringLiteral("W_bubble"));
        W_bubble->setGeometry(QRect(10, 20, 81, 31));
        groupBox_78 = new QGroupBox(Write_back);
        groupBox_78->setObjectName(QStringLiteral("groupBox_78"));
        groupBox_78->setGeometry(QRect(110, 20, 101, 61));
        W_valE = new QTextBrowser(groupBox_78);
        W_valE->setObjectName(QStringLiteral("W_valE"));
        W_valE->setGeometry(QRect(10, 20, 81, 31));
        groupBox_71 = new QGroupBox(Write_back);
        groupBox_71->setObjectName(QStringLiteral("groupBox_71"));
        groupBox_71->setGeometry(QRect(210, 90, 101, 61));
        W_dstM = new QTextBrowser(groupBox_71);
        W_dstM->setObjectName(QStringLiteral("W_dstM"));
        W_dstM->setGeometry(QRect(10, 20, 81, 31));
        groupBox_81 = new QGroupBox(Write_back);
        groupBox_81->setObjectName(QStringLiteral("groupBox_81"));
        groupBox_81->setGeometry(QRect(10, 90, 101, 61));
        W_icode = new QTextBrowser(groupBox_81);
        W_icode->setObjectName(QStringLiteral("W_icode"));
        W_icode->setGeometry(QRect(10, 20, 81, 31));
        groupBox_82 = new QGroupBox(Write_back);
        groupBox_82->setObjectName(QStringLiteral("groupBox_82"));
        groupBox_82->setGeometry(QRect(210, 20, 101, 61));
        W_dstE = new QTextBrowser(groupBox_82);
        W_dstE->setObjectName(QStringLiteral("W_dstE"));
        W_dstE->setGeometry(QRect(10, 20, 81, 31));
        groupBox_83 = new QGroupBox(Write_back);
        groupBox_83->setObjectName(QStringLiteral("groupBox_83"));
        groupBox_83->setGeometry(QRect(339, 140, 101, 61));
        W_stall = new QTextBrowser(groupBox_83);
        W_stall->setObjectName(QStringLiteral("W_stall"));
        W_stall->setGeometry(QRect(10, 20, 81, 31));
        groupBox_84 = new QGroupBox(Write_back);
        groupBox_84->setObjectName(QStringLiteral("groupBox_84"));
        groupBox_84->setGeometry(QRect(110, 90, 101, 61));
        W_valM = new QTextBrowser(groupBox_84);
        W_valM->setObjectName(QStringLiteral("W_valM"));
        W_valM->setGeometry(QRect(10, 20, 81, 31));
        groupBox_85 = new QGroupBox(Write_back);
        groupBox_85->setObjectName(QStringLiteral("groupBox_85"));
        groupBox_85->setGeometry(QRect(10, 20, 101, 61));
        W_STAT = new QTextBrowser(groupBox_85);
        W_STAT->setObjectName(QStringLiteral("W_STAT"));
        W_STAT->setGeometry(QRect(10, 20, 81, 31));
        Pipeline->addTab(Write_back, QString());
        groupBox = new QGroupBox(Main);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(20, 330, 181, 61));
        STAT = new QTextBrowser(groupBox);
        STAT->setObjectName(QStringLiteral("STAT"));
        STAT->setGeometry(QRect(10, 20, 161, 31));
        groupBox_2 = new QGroupBox(Main);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(280, 330, 181, 161));
        ZFBOX = new QGroupBox(groupBox_2);
        ZFBOX->setObjectName(QStringLiteral("ZFBOX"));
        ZFBOX->setGeometry(QRect(10, 20, 71, 61));
        ZF = new QTextBrowser(ZFBOX);
        ZF->setObjectName(QStringLiteral("ZF"));
        ZF->setGeometry(QRect(10, 20, 51, 31));
        OFBOX = new QGroupBox(groupBox_2);
        OFBOX->setObjectName(QStringLiteral("OFBOX"));
        OFBOX->setGeometry(QRect(100, 20, 71, 61));
        OF = new QTextBrowser(OFBOX);
        OF->setObjectName(QStringLiteral("OF"));
        OF->setGeometry(QRect(10, 20, 51, 31));
        SFBOX = new QGroupBox(groupBox_2);
        SFBOX->setObjectName(QStringLiteral("SFBOX"));
        SFBOX->setGeometry(QRect(10, 90, 71, 61));
        SF = new QTextBrowser(SFBOX);
        SF->setObjectName(QStringLiteral("SF"));
        SF->setGeometry(QRect(10, 20, 51, 31));
        CFBOX = new QGroupBox(groupBox_2);
        CFBOX->setObjectName(QStringLiteral("CFBOX"));
        CFBOX->setGeometry(QRect(100, 90, 71, 61));
        CF = new QTextBrowser(CFBOX);
        CF->setObjectName(QStringLiteral("CF"));
        CF->setGeometry(QRect(10, 20, 51, 31));
        groupBox_3 = new QGroupBox(Main);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(20, 400, 181, 61));
        cycle = new QTextBrowser(groupBox_3);
        cycle->setObjectName(QStringLiteral("cycle"));
        cycle->setGeometry(QRect(10, 20, 161, 31));
        groupBox_4 = new QGroupBox(Main);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 490, 471, 141));
        label_ebx = new QLabel(groupBox_4);
        label_ebx->setObjectName(QStringLiteral("label_ebx"));
        label_ebx->setGeometry(QRect(10, 60, 48, 21));
        label_eax = new QLabel(groupBox_4);
        label_eax->setObjectName(QStringLiteral("label_eax"));
        label_eax->setGeometry(QRect(10, 20, 51, 21));
        label_ecx = new QLabel(groupBox_4);
        label_ecx->setObjectName(QStringLiteral("label_ecx"));
        label_ecx->setGeometry(QRect(170, 20, 48, 21));
        label_edx = new QLabel(groupBox_4);
        label_edx->setObjectName(QStringLiteral("label_edx"));
        label_edx->setGeometry(QRect(320, 20, 48, 21));
        text_eax = new QTextBrowser(groupBox_4);
        text_eax->setObjectName(QStringLiteral("text_eax"));
        text_eax->setGeometry(QRect(60, 20, 91, 31));
        text_ecx = new QTextBrowser(groupBox_4);
        text_ecx->setObjectName(QStringLiteral("text_ecx"));
        text_ecx->setGeometry(QRect(220, 20, 91, 31));
        text_edx = new QTextBrowser(groupBox_4);
        text_edx->setObjectName(QStringLiteral("text_edx"));
        text_edx->setGeometry(QRect(370, 20, 91, 31));
        text_ebx = new QTextBrowser(groupBox_4);
        text_ebx->setObjectName(QStringLiteral("text_ebx"));
        text_ebx->setGeometry(QRect(60, 60, 91, 31));
        text_esp = new QTextBrowser(groupBox_4);
        text_esp->setObjectName(QStringLiteral("text_esp"));
        text_esp->setGeometry(QRect(220, 60, 91, 31));
        label_ebp = new QLabel(groupBox_4);
        label_ebp->setObjectName(QStringLiteral("label_ebp"));
        label_ebp->setGeometry(QRect(320, 60, 48, 29));
        label_esi = new QLabel(groupBox_4);
        label_esi->setObjectName(QStringLiteral("label_esi"));
        label_esi->setGeometry(QRect(170, 100, 48, 21));
        label_edi = new QLabel(groupBox_4);
        label_edi->setObjectName(QStringLiteral("label_edi"));
        label_edi->setGeometry(QRect(10, 100, 48, 21));
        label_esp = new QLabel(groupBox_4);
        label_esp->setObjectName(QStringLiteral("label_esp"));
        label_esp->setGeometry(QRect(170, 60, 48, 31));
        text_edi = new QTextBrowser(groupBox_4);
        text_edi->setObjectName(QStringLiteral("text_edi"));
        text_edi->setGeometry(QRect(60, 100, 91, 31));
        text_esi = new QTextBrowser(groupBox_4);
        text_esi->setObjectName(QStringLiteral("text_esi"));
        text_esi->setGeometry(QRect(220, 100, 91, 31));
        text_ebp = new QTextBrowser(groupBox_4);
        text_ebp->setObjectName(QStringLiteral("text_ebp"));
        text_ebp->setGeometry(QRect(370, 60, 91, 31));
        label_ebx->raise();
        label_eax->raise();
        label_ecx->raise();
        label_edx->raise();
        text_eax->raise();
        text_ecx->raise();
        text_edx->raise();
        text_ebx->raise();
        text_esp->raise();
        label_ebp->raise();
        label_esi->raise();
        label_edi->raise();
        label_esp->raise();
        label_esp->raise();
        text_edi->raise();
        text_esi->raise();
        text_ebp->raise();
        Monitor->addTab(Main, QString());
        Pipeline->raise();
        groupBox->raise();
        groupBox_2->raise();
        groupBox_3->raise();
        groupBox_4->raise();
        label_edi->raise();
        label_esi->raise();
        label_esp->raise();
        Operation = new QWidget();
        Operation->setObjectName(QStringLiteral("Operation"));
        Pipeline_2 = new QTabWidget(Operation);
        Pipeline_2->setObjectName(QStringLiteral("Pipeline_2"));
        Pipeline_2->setGeometry(QRect(20, 20, 461, 251));
        Fetch_2 = new QWidget();
        Fetch_2->setObjectName(QStringLiteral("Fetch_2"));
        f_opt = new QTextBrowser(Fetch_2);
        f_opt->setObjectName(QStringLiteral("f_opt"));
        f_opt->setGeometry(QRect(10, 40, 431, 171));
        Pipeline_2->addTab(Fetch_2, QString());
        Decode_2 = new QWidget();
        Decode_2->setObjectName(QStringLiteral("Decode_2"));
        d_opt = new QTextBrowser(Decode_2);
        d_opt->setObjectName(QStringLiteral("d_opt"));
        d_opt->setGeometry(QRect(10, 40, 431, 171));
        Pipeline_2->addTab(Decode_2, QString());
        Execute_2 = new QWidget();
        Execute_2->setObjectName(QStringLiteral("Execute_2"));
        e_opt = new QTextBrowser(Execute_2);
        e_opt->setObjectName(QStringLiteral("e_opt"));
        e_opt->setGeometry(QRect(10, 40, 431, 171));
        Pipeline_2->addTab(Execute_2, QString());
        Memory_2 = new QWidget();
        Memory_2->setObjectName(QStringLiteral("Memory_2"));
        m_opt = new QTextBrowser(Memory_2);
        m_opt->setObjectName(QStringLiteral("m_opt"));
        m_opt->setGeometry(QRect(10, 40, 431, 171));
        Pipeline_2->addTab(Memory_2, QString());
        Write_back_2 = new QWidget();
        Write_back_2->setObjectName(QStringLiteral("Write_back_2"));
        w_opt = new QTextBrowser(Write_back_2);
        w_opt->setObjectName(QStringLiteral("w_opt"));
        w_opt->setGeometry(QRect(10, 40, 431, 171));
        Pipeline_2->addTab(Write_back_2, QString());
        Monitor->addTab(Operation, QString());
        Memory1 = new QWidget();
        Memory1->setObjectName(QStringLiteral("Memory1"));
        memorymonitor = new QTextBrowser(Memory1);
        memorymonitor->setObjectName(QStringLiteral("memorymonitor"));
        memorymonitor->setGeometry(QRect(30, 20, 321, 381));
        Monitor->addTab(Memory1, QString());
        path = new QLineEdit(centralWidget);
        path->setObjectName(QStringLiteral("path"));
        path->setGeometry(QRect(140, 630, 141, 31));
        Button_run = new QPushButton(centralWidget);
        Button_run->setObjectName(QStringLiteral("Button_run"));
        Button_run->setGeometry(QRect(240, 590, 91, 31));
        Button_stop = new QPushButton(centralWidget);
        Button_stop->setObjectName(QStringLiteral("Button_stop"));
        Button_stop->setGeometry(QRect(340, 590, 91, 31));
        groupBox_10 = new QGroupBox(centralWidget);
        groupBox_10->setObjectName(QStringLiteral("groupBox_10"));
        groupBox_10->setGeometry(QRect(290, 620, 141, 71));
        speed = new QSlider(groupBox_10);
        speed->setObjectName(QStringLiteral("speed"));
        speed->setGeometry(QRect(20, 20, 101, 21));
        speed->setMinimum(1);
        speed->setValue(50);
        speed->setOrientation(Qt::Horizontal);
        label = new QLabel(groupBox_10);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(100, 50, 16, 16));
        nowspeed = new QLabel(groupBox_10);
        nowspeed->setObjectName(QStringLiteral("nowspeed"));
        nowspeed->setGeometry(QRect(40, 50, 54, 12));
        path_code = new QLineEdit(centralWidget);
        path_code->setObjectName(QStringLiteral("path_code"));
        path_code->setGeometry(QRect(240, 550, 141, 31));
        Button_code = new QPushButton(centralWidget);
        Button_code->setObjectName(QStringLiteral("Button_code"));
        Button_code->setGeometry(QRect(40, 550, 91, 31));
        Button_clear = new QPushButton(centralWidget);
        Button_clear->setObjectName(QStringLiteral("Button_clear"));
        Button_clear->setGeometry(QRect(140, 550, 91, 31));
        groupBox_11 = new QGroupBox(centralWidget);
        groupBox_11->setObjectName(QStringLiteral("groupBox_11"));
        groupBox_11->setGeometry(QRect(10, 10, 411, 531));
        Code = new QTextBrowser(groupBox_11);
        Code->setObjectName(QStringLiteral("Code"));
        Code->setGeometry(QRect(20, 20, 381, 491));
        Code->setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        Code->setHorizontalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        Code->setSizeAdjustPolicy(QAbstractScrollArea::AdjustIgnored);
        Code->setLineWrapMode(QTextEdit::NoWrap);
        MainWindow->setCentralWidget(centralWidget);
        Button_reset->raise();
        Button_next->raise();
        Button_load->raise();
        Monitor->raise();
        path->raise();
        Button_run->raise();
        Button_stop->raise();
        groupBox_10->raise();
        path_code->raise();
        Button_code->raise();
        Button_clear->raise();
        speed->raise();
        groupBox_11->raise();

        retranslateUi(MainWindow);

        Monitor->setCurrentIndex(0);
        Pipeline->setCurrentIndex(0);
        Pipeline_2->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        Button_reset->setText(QApplication::translate("MainWindow", "Reset", Q_NULLPTR));
        Button_next->setText(QApplication::translate("MainWindow", "Next", Q_NULLPTR));
        Button_load->setText(QApplication::translate("MainWindow", "Load File", Q_NULLPTR));
        groupBox_5->setTitle(QApplication::translate("MainWindow", "F_predPC", Q_NULLPTR));
        groupBox_6->setTitle(QApplication::translate("MainWindow", "f_predPC", Q_NULLPTR));
        groupBox_7->setTitle(QApplication::translate("MainWindow", "STAT", Q_NULLPTR));
        groupBox_8->setTitle(QApplication::translate("MainWindow", "STALL", Q_NULLPTR));
        groupBox_9->setTitle(QApplication::translate("MainWindow", "BUBBLE", Q_NULLPTR));
        groupBox_13->setTitle(QApplication::translate("MainWindow", "ifun", Q_NULLPTR));
        groupBox_14->setTitle(QApplication::translate("MainWindow", "icode", Q_NULLPTR));
        Pipeline->setTabText(Pipeline->indexOf(Fetch), QApplication::translate("MainWindow", "Fetch", Q_NULLPTR));
        groupBox_17->setTitle(QApplication::translate("MainWindow", "valP", Q_NULLPTR));
        groupBox_18->setTitle(QApplication::translate("MainWindow", "BUBBLE", Q_NULLPTR));
        groupBox_19->setTitle(QApplication::translate("MainWindow", "STALL", Q_NULLPTR));
        groupBox_20->setTitle(QApplication::translate("MainWindow", "rB", Q_NULLPTR));
        groupBox_21->setTitle(QApplication::translate("MainWindow", "STAT", Q_NULLPTR));
        groupBox_23->setTitle(QApplication::translate("MainWindow", "icode", Q_NULLPTR));
        groupBox_24->setTitle(QApplication::translate("MainWindow", "rA", Q_NULLPTR));
        groupBox_25->setTitle(QApplication::translate("MainWindow", "valC", Q_NULLPTR));
        groupBox_26->setTitle(QApplication::translate("MainWindow", "ifun", Q_NULLPTR));
        Pipeline->setTabText(Pipeline->indexOf(Decode), QApplication::translate("MainWindow", "Decode", Q_NULLPTR));
        groupBox_28->setTitle(QApplication::translate("MainWindow", "STALL", Q_NULLPTR));
        groupBox_29->setTitle(QApplication::translate("MainWindow", "STAT", Q_NULLPTR));
        groupBox_30->setTitle(QApplication::translate("MainWindow", "BUBBLE", Q_NULLPTR));
        groupBox_31->setTitle(QApplication::translate("MainWindow", "ifun", Q_NULLPTR));
        groupBox_32->setTitle(QApplication::translate("MainWindow", "valC", Q_NULLPTR));
        groupBox_33->setTitle(QApplication::translate("MainWindow", "dstM", Q_NULLPTR));
        groupBox_34->setTitle(QApplication::translate("MainWindow", "dstE", Q_NULLPTR));
        groupBox_35->setTitle(QApplication::translate("MainWindow", "valA", Q_NULLPTR));
        groupBox_36->setTitle(QApplication::translate("MainWindow", "icode", Q_NULLPTR));
        groupBox_37->setTitle(QApplication::translate("MainWindow", "valB", Q_NULLPTR));
        groupBox_38->setTitle(QApplication::translate("MainWindow", "srcA", Q_NULLPTR));
        groupBox_39->setTitle(QApplication::translate("MainWindow", "srcB", Q_NULLPTR));
        Pipeline->setTabText(Pipeline->indexOf(Execute), QApplication::translate("MainWindow", "Execute", Q_NULLPTR));
        groupBox_69->setTitle(QApplication::translate("MainWindow", "dstM", Q_NULLPTR));
        groupBox_70->setTitle(QApplication::translate("MainWindow", "icode", Q_NULLPTR));
        groupBox_72->setTitle(QApplication::translate("MainWindow", "BUBBLE", Q_NULLPTR));
        groupBox_73->setTitle(QApplication::translate("MainWindow", "valE", Q_NULLPTR));
        groupBox_74->setTitle(QApplication::translate("MainWindow", "dstE", Q_NULLPTR));
        groupBox_75->setTitle(QApplication::translate("MainWindow", "valA", Q_NULLPTR));
        groupBox_77->setTitle(QApplication::translate("MainWindow", "Cnd", Q_NULLPTR));
        groupBox_79->setTitle(QApplication::translate("MainWindow", "STAT", Q_NULLPTR));
        groupBox_80->setTitle(QApplication::translate("MainWindow", "STALL", Q_NULLPTR));
        Pipeline->setTabText(Pipeline->indexOf(Memory), QApplication::translate("MainWindow", "Memory", Q_NULLPTR));
        groupBox_76->setTitle(QApplication::translate("MainWindow", "BUBBLE", Q_NULLPTR));
        groupBox_78->setTitle(QApplication::translate("MainWindow", "valE", Q_NULLPTR));
        groupBox_71->setTitle(QApplication::translate("MainWindow", "dstM", Q_NULLPTR));
        groupBox_81->setTitle(QApplication::translate("MainWindow", "icode", Q_NULLPTR));
        groupBox_82->setTitle(QApplication::translate("MainWindow", "dstE", Q_NULLPTR));
        groupBox_83->setTitle(QApplication::translate("MainWindow", "STALL", Q_NULLPTR));
        groupBox_84->setTitle(QApplication::translate("MainWindow", "valM", Q_NULLPTR));
        groupBox_85->setTitle(QApplication::translate("MainWindow", "STAT", Q_NULLPTR));
        Pipeline->setTabText(Pipeline->indexOf(Write_back), QApplication::translate("MainWindow", "Write_back", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("MainWindow", "STAT", Q_NULLPTR));
        STAT->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", Q_NULLPTR));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "Condition Code", Q_NULLPTR));
        ZFBOX->setTitle(QApplication::translate("MainWindow", "ZF", Q_NULLPTR));
        OFBOX->setTitle(QApplication::translate("MainWindow", "OF", Q_NULLPTR));
        SFBOX->setTitle(QApplication::translate("MainWindow", "SF", Q_NULLPTR));
        CFBOX->setTitle(QApplication::translate("MainWindow", "CF", Q_NULLPTR));
        groupBox_3->setTitle(QApplication::translate("MainWindow", "Cycle", Q_NULLPTR));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "Register", Q_NULLPTR));
        label_ebx->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">%ebx</span></p></body></html>", Q_NULLPTR));
        label_eax->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">%eax</span></p></body></html>", Q_NULLPTR));
        label_ecx->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">%ecx</span></p></body></html>", Q_NULLPTR));
        label_edx->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">%edx</span></p></body></html>", Q_NULLPTR));
        label_ebp->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">%ebp</span></p></body></html>", Q_NULLPTR));
        label_esi->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">%esi</span></p></body></html>", Q_NULLPTR));
        label_edi->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">%edi</span></p></body></html>", Q_NULLPTR));
        label_esp->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">%esp</span></p></body></html>", Q_NULLPTR));
        Monitor->setTabText(Monitor->indexOf(Main), QApplication::translate("MainWindow", "Main", Q_NULLPTR));
        Pipeline_2->setTabText(Pipeline_2->indexOf(Fetch_2), QApplication::translate("MainWindow", "Fetch", Q_NULLPTR));
        Pipeline_2->setTabText(Pipeline_2->indexOf(Decode_2), QApplication::translate("MainWindow", "Decode", Q_NULLPTR));
        Pipeline_2->setTabText(Pipeline_2->indexOf(Execute_2), QApplication::translate("MainWindow", "Execute", Q_NULLPTR));
        Pipeline_2->setTabText(Pipeline_2->indexOf(Memory_2), QApplication::translate("MainWindow", "Memory", Q_NULLPTR));
        Pipeline_2->setTabText(Pipeline_2->indexOf(Write_back_2), QApplication::translate("MainWindow", "Write_back", Q_NULLPTR));
        Monitor->setTabText(Monitor->indexOf(Operation), QApplication::translate("MainWindow", "Operation", Q_NULLPTR));
        Monitor->setTabText(Monitor->indexOf(Memory1), QApplication::translate("MainWindow", "Memory", Q_NULLPTR));
        path->setText(QApplication::translate("MainWindow", "File Path", Q_NULLPTR));
        Button_run->setText(QApplication::translate("MainWindow", "Run", Q_NULLPTR));
        Button_stop->setText(QApplication::translate("MainWindow", "Stop", Q_NULLPTR));
        groupBox_10->setTitle(QApplication::translate("MainWindow", "Running speed", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "Hz", Q_NULLPTR));
        nowspeed->setText(QApplication::translate("MainWindow", "50", Q_NULLPTR));
        path_code->setText(QApplication::translate("MainWindow", "Code Path", Q_NULLPTR));
        Button_code->setText(QApplication::translate("MainWindow", "Load Code", Q_NULLPTR));
        Button_clear->setText(QApplication::translate("MainWindow", "Clear", Q_NULLPTR));
        groupBox_11->setTitle(QApplication::translate("MainWindow", " Codebox", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SIMULATOR_H
